import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'

const primary = Sora({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-primary',
})

export const metadata: Metadata = {
  title: 'Mahdi Portfolio',
  description: 'Mahdi Portfolio Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${primary.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  )
}
